// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 13,
  states: "tQVQPOOOOQO'#C_'#C_OOQO'#Cf'#CfOOQO'#Cb'#CbQVQPOOOOQO-E6`-E6`",
  stateData: "e~OXOS~OQQOSQOTQOZPO~O",
  goto: "jZPPP[PP`PPPfTQOSQSORTSTROS",
  nodeNames: "⚠ Program Identifier String Tag Statement",
  maxTerm: 11,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "&`~R]XYzYZz]^zpqzrs!]uv%^wx!]!Q![%i!c!}%i#R#S%i#T#o%i#o#p%z#q#r&Y~!PSX~XYzYZz]^zpqz~!`Wpq!]qr!]rs!xsw!]wx!}x#O!]#O#P#l#P~!]~!}OZ~~#SWZ~pq!]qr!]rs!xsw!]wx!}x#O!]#O#P#l#P~!]~#oXrs!]!P!Q!]#O#P!]#U#V!]#Y#Z!]#b#c!]#f#g!]#h#i!]#i#j$[~$_R!Q![$h!c!i$h#T#Z$h~$kR!Q![$t!c!i$t#T#Z$t~$wR!Q![%Q!c!i%Q#T#Z%Q~%TR!Q![!]!c!i!]#T#Z!]~%aP#q#r%d~%iOS~~%nSQ~!Q![%i!c!}%i#R#S%i#T#o%i~%}Quv%d#o#p&T~&YOT~~&]P#q#r&T",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
